import Header from "@/components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import { fetchGenerations } from "@/services/api.service";
import Breadcrumbs from "@/components/Breadcrumbs";
import GenerationListing from "@/components/GenerationsPage/GenerationListing";
import GenerationsPageWrapper from "@/components/GenerationsPage/GenerationsPageWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = {
  children: React.ReactNode;
};

export default async function RootLayout({ children }: LayoutProps) {
  const generations = await fetchGenerations();

  return (
    <html lang="en">
      <body className="h-screen pt-14">
        <Header />
        <Breadcrumbs generations={generations} />
        <main className="overflow-y-auto" style={{ height: "calc(100vh - 135px)" }}>
          <div className="grid-cols-12 px-5 m-auto max-w-screen-2xl lg:grid lg:mt-8 lg:divide-x-2 lg:divide-solid lg:gap-x-5 2xl:gap-x-10 2xl:px-0">
            <GenerationsPageWrapper>
              <h3 className="mb-3 text-3xl font-bold text-gray-700">Generations</h3>
              <GenerationListing generations={generations} />
            </GenerationsPageWrapper>
            {children}
          </div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
